- name: Deploy to DigitalOcean
        run: |
          ssh -i ~/.ssh/id_rsa root@139.59.1.105 << 'EOF'
            set -e  # Exit immediately if any command fails
            
            echo "Navigating to the app directory..."
            cd /var/www/ajaysapi.resolutesolutions.in.net/public_html
            
            echo "Initializing Git repository..."
            git init
            
            echo "Configuring Git remote..."
            if ! git remote | grep -q '^origin$'; then
                git remote add origin git@github.com:Ashishresolut/ajays.git
            fi
            
            echo "Fetching latest code..."
            git fetch origin
            git reset --hard origin/main
            
            echo "Installing dependencies..."
            npm install --force
            
            echo "Restarting the app..."
            pm2 delete ajays || true
            pm2 start ajays.js --name ajays
            
            echo "Deployment completed!"
          EOF
