on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Deploy to DigitalOcean
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa root@139.59.1.105 << 'EOF'
            echo "Starting deployment..."

            cd /var/www/ajaysapi.resolutesolutions.in.net/public_html || exit

            if [ ! -d .git ]; then
              echo "Initializing Git repository..."
              git init
              git remote add origin git@github.com:Ashishresolut/ajays.git
            fi

            echo "Fetching and resetting to the latest code..."
            git fetch origin
            git reset --hard origin/main

            echo "Installing dependencies..."
            npm install

            echo "Stopping existing app..."
            pm2 delete ajays || true

            echo "Starting app..."
            pm2 start ajays.js --name ajays

            echo "Deployment complete!"
          EOF
