name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    
    strategy:
      matrix:
        node-version: [14, 16, 18]  # You can add specific Node.js versions here

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies and build frontend
        run: |
          npm install
          cd frontend
          npm install
          npm run build
          cd ..

      - name: Stop and restart the app with PM2
        run: |
          pm2 stop 0 || true  # Ensure it does not fail if PM2 is not running
          pm2 start 0
          pm2 save

      - name: Restart Apache service
        run: |
          sudo service apache2 restart
